#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-conversaotemperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-conversaotemperatura
  template:
    metadata:
      labels:
        app: web-conversaotemperatura
    spec: #pod
      containers:
        - name: web-conversaotemperatura
          image: throne82/conversao-temperatura:latest
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 8080
---
#service 
apiVersion: v1
kind: Service
metadata:
  name: web-conversaotemperatura
spec:
  selector:
    app: web-conversaotemperatura
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort